### ISSUE TITLE
I've a control library but I don't know how to add to this page

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaCommunity/awesome-avalonia#12]
hi, I've a control library and I want to add it to this page, but I don't know how to do it :(

**Comment by OmidID** [comment]
Hello @PieroCastillo ,
are you talking about this repo: https://github.com/PieroCastillo/Aura.UI

**Comment by PieroCastillo** [comment]
> Hello @PieroCastillo ,
> are you talking about this repo: https://github.com/PieroCastillo/Aura.UI

exactly, I wanna add that repository and in the future add this another, https://github.com/PieroCastillo/AuraDraw

**Comment by FoggyFinder** [comment]
You can make a fork:

https://docs.github.com/en/github/getting-started-with-github/fork-a-repo

and create PR 

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
