### ISSUE TITLE
Consider keeping lists in alphabetical order

### ISSUE THREAD

**Issue by rstm-sf** [AvaloniaCommunity/awesome-avalonia#15]
Hello!

Consider keeping lists in alphabetical order. It seems to me that it will look better this way

**Comment by OmidID** [comment]
Not a bad idea. You are welcome to push changes. :)

**Comment by rstm-sf** [comment]
Is it possible to do something like that: [1](https://github.com/ForNeVeR/wpf-math/blob/af5c330fecdaec39e85324292372228350724a2a/scripts/verify-encoding.ps1#L3) and [2](https://github.com/ForNeVeR/wpf-math/blob/af5c330fecdaec39e85324292372228350724a2a/appveyor.yml#L3-L4)?
Unfortunately, apart from an idea, nothing else comes to my mind (hopefully temporarily ...)

**Comment by nlogozzo** [comment]
Solved with PR #26
