### ISSUE TITLE
Add a link to CefGlue

### ISSUE THREAD

**Issue by grokys** [AvaloniaCommunity/awesome-avalonia#2]
Not sure what section this should be in, but here's the link:

https://gitlab.com/joaompneves/cefglue/

And a tweet explaining what it is:

https://twitter.com/joaomiguelneves/status/1224988129314201600

**Comment by OmidID** [comment]
@grokys Thanks 
I can see in another awesome page it has a separate section `Web Browser`

https://github.com/quozd/awesome-dotnet#web-browsers
https://github.com/myfreeweb/awesome-gtk#web-browsers

**Comment by OmidID** [comment]
@grokys 
I found out another project it's really same 
https://github.com/CefNet/CefNet
I asking there to be sure they are not same project and then I'll create a Web Browser section under Library.

**Comment by grokys** [comment]
The developer that's working on it is doing so at https://gitlab.com/joaompneves/cefglue/ so it's probably best to use that URL.

**Comment by OmidID** [comment]
@grokys CefNet's developer mention that has another approach. I added them both.
https://github.com/CefNet/CefNet/issues/1
