### ISSUE TITLE
Can add Example project use avalonia fluent theme vs Native AOT (CoreRT)?

### ISSUE THREAD

**Issue by unominhtuan** [AvaloniaCommunity/awesome-avalonia#27]
I am using avalonia default theme with native AOT. But I cannot use the new Fluent Theme with Native AOT, the app cannot launch after packaging. Can I add a sample project? thank you very much.

**Comment by OmidID** [comment]
If you have a problem is better to ask on the [Avalonia](https://github.com/AvaloniaUI/Avalonia) project page or you can ask the community in [Gitter ](https://gitter.im/AvaloniaUI/Avalonia)

**Comment by maxkatz6** [comment]
Useful issue thread https://github.com/AvaloniaUI/Avalonia/issues/1476
And this example project is kept up to date https://github.com/teobugslayer/AvaloniaCoreRTDemo
