### ISSUE TITLE
Consider adding MarkDoc.Core

### ISSUE THREAD

**Issue by hailstorm75** [AvaloniaCommunity/awesome-avalonia#68]
Please consider adding my project which uses Avalonia and FluentAvaloniaUI - [MarkDoc.Core](https://github.com/hailstorm75/MarkDoc.Core).

**Description**
Documentation generating tool for .NET libraries.

**Category**
Samples and Projects

**Comment by OmidID** [comment]
@hailstorm75 Please create a PR

**Comment by hailstorm75** [comment]
Create PR #69 (nice)
